### ISSUE TITLE
TODO LIST before production

### ISSUE THREAD

**Issue by nathangobinet** [nathangobinet/armorydesbuissons#7]
- [x] Faire le fichier _error (et check si il y'en a pas un autre)
- [x] Faire une page legals ?
- [x] Résoudre pb de build en prod mode
- [x] Essayer de re résoudre PB socket (react update on unmounted component)
- [x] Put title and metadata on each page
- [x] Favicon
- [x] Add GA
- [x] Check the front end check list
